### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by rebelga** [anowell/mia#22]
Installed via .deb on KDE Neon (Ubuntu 16.04).  Ran "algo auth" and entered my API key.  Then ran "algo ls" as suggested.  Result:

`Error listing directory: http error: The OpenSSL library reported an error: , error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed`

.algorithmia looks good.  openssl version gives "OpenSSL 1.1.0g  2 Nov 2017"

**Comment by anowell** [comment]
Digging in a bit: my working theory here is that you're using an outdated version of this CLI that was built against openssl differently, but I think this is the result of the [`README.md` being outdated with old install instructions](https://github.com/algorithmiaio/algorithmia-cli/commit/500ff8c97f36a5b2ae4344a45f5dcffbdc076415) for the `deb` archive. 

I grabbed a ubuntu 16.04 install and while it only had `OpenSSL 1.0.2g 1 Mar 2016`, it did have the same error when using the `v1.0.0-beta.3` version of the algorithmia CLI, but not `v1.0.1`. 

```
apt-get remove algorithmia
curl -OL https://github.com/algorithmiaio/algorithmia-cli/releases/download/v1.0.1/algorithmia-v1.0.1-x86_64-unknown-linux-gnu.deb
sudo dpkg -i algorithmia-v1.0.1-x86_64-unknown-linux-gnu.deb
```

Also note, that if upgrading from `v1.0.0-beta.3` to `v1.0.1`, the config file location has changed a bit. The [install script]( https://algorithmia.com/install.sh) handles this migration automatically, but the `deb` install does not, so you'll need to move `~/.algorithmia` to `~/.algorithmia/config`.

(If I'm mistaken about the version you have, let me know, and I'll keep digging into openssl build issues).

**Comment by rebelga** [comment]
Thanks Anthony, that was it exactly.
